### Imports:

In [1]:
import numpy as np
import pandas as pd
from Modelo_cripto_SVM import Modelo_cripto_SVM

### Teste do Modelo 1:

In [2]:
y_vals = pd.Series(np.random.random(100).round())
aux_dict = {0:-1, 1:1}
y_vals = y_vals.map(aux_dict).to_numpy()
y_vals

array([-1, -1, -1,  1,  1,  1, -1, -1,  1, -1,  1,  1,  1, -1, -1,  1,  1,
        1,  1, -1, -1, -1,  1,  1, -1,  1,  1, -1, -1, -1, -1,  1,  1,  1,
       -1, -1,  1,  1,  1, -1, -1,  1,  1, -1,  1,  1,  1, -1,  1,  1,  1,
        1,  1, -1,  1,  1,  1,  1, -1, -1, -1, -1, -1,  1,  1, -1, -1,  1,
       -1,  1,  1,  1,  1, -1, -1,  1, -1,  1,  1, -1,  1,  1,  1, -1, -1,
        1, -1,  1,  1,  1, -1, -1, -1,  1,  1, -1,  1,  1,  1, -1],
      dtype=int64)

In [3]:
n = len(y_vals)
n

x_vals = dict()
for j in range(n):
    x_vals[j] = (np.random.random(100) - 0.5)

Sigma = np.zeros((n, n))
for i in range(n):
    for j in range(n):
        Sigma[i, j] = (x_vals[i] * x_vals[j]).sum()

Sigma

array([[ 7.82393923e+00,  5.92247307e-01, -8.37594066e-01, ...,
        -1.59852315e+00,  3.41512187e-01,  5.23576084e-01],
       [ 5.92247307e-01,  8.06835043e+00, -1.32453197e+00, ...,
        -1.30002893e-01, -8.18081596e-03,  7.12662384e-01],
       [-8.37594066e-01, -1.32453197e+00,  7.72217869e+00, ...,
        -9.56455292e-01, -8.17284218e-01, -1.37429667e+00],
       ...,
       [-1.59852315e+00, -1.30002893e-01, -9.56455292e-01, ...,
         8.51613237e+00,  7.60974830e-01, -1.95570672e+00],
       [ 3.41512187e-01, -8.18081596e-03, -8.17284218e-01, ...,
         7.60974830e-01,  8.56002866e+00, -1.04424632e+00],
       [ 5.23576084e-01,  7.12662384e-01, -1.37429667e+00, ...,
        -1.95570672e+00, -1.04424632e+00,  9.43763831e+00]])

In [4]:
lambda_val = 1
lambda_val

1

In [5]:
modelo = Modelo_cripto_SVM(Sigma, y_vals, lambda_val)
d_vals = modelo.solve(log=0)

Academic license - for non-commercial use only - expires 2021-11-05
Using license file C:\Users\Eduardo\gurobi.lic


In [6]:
d_vals.round(6)

array([-5.000e-03, -5.000e-03, -5.000e-03,  4.585e-03,  5.000e-03,
        3.163e-03, -5.000e-03, -5.000e-03,  4.762e-03, -5.000e-03,
        5.000e-03,  0.000e+00,  0.000e+00, -5.000e-03, -5.000e-03,
        5.000e-03,  5.000e-03,  5.000e-03,  4.494e-03, -5.000e-03,
       -5.000e-03, -5.000e-03,  5.000e-03,  5.000e-03, -5.000e-03,
        0.000e+00,  5.000e-03, -5.000e-03, -5.000e-03, -5.000e-03,
       -5.000e-03,  1.288e-03,  2.304e-03,  1.607e-03, -5.000e-03,
       -5.000e-03,  5.000e-03,  5.000e-03,  5.000e-03, -5.000e-03,
       -5.000e-03,  5.000e-03,  5.000e-03, -5.000e-03,  5.000e-03,
        5.000e-03,  3.253e-03, -5.000e-03,  2.322e-03,  3.972e-03,
        2.862e-03,  5.000e-03,  5.000e-03, -5.000e-03,  5.000e-03,
        5.000e-03,  5.000e-03,  5.000e-03, -5.000e-03, -5.000e-03,
       -5.000e-03, -5.000e-03, -5.000e-03,  0.000e+00,  3.896e-03,
       -5.000e-03, -5.000e-03,  5.000e-03, -5.000e-03,  4.315e-03,
        8.620e-04,  5.000e-03,  5.000e-03, -5.000e-03, -5.000e

In [21]:
modelo.update_lambda(20)
modelo.lambda_val
(modelo.solve() - d_vals).max()
modelo.solve().round(6)

array([ 5.000e-03,  5.000e-03,  5.000e-03,  5.000e-03,  5.000e-03,
       -1.600e-05, -5.000e-03,  5.000e-03, -2.850e-03,  5.000e-03,
        5.000e-03, -5.000e-03,  5.000e-03,  5.000e-03,  5.000e-03,
        5.000e-03,  5.000e-03, -5.000e-03, -5.000e-03,  5.000e-03,
        5.000e-03, -5.000e-03, -5.000e-03,  5.000e-03, -5.000e-03,
        5.000e-03, -5.000e-03,  5.000e-03,  5.000e-03, -5.000e-03,
        5.000e-03, -5.000e-03,  5.000e-03, -5.000e-03,  5.000e-03,
       -5.000e-03,  5.000e-03,  5.000e-03,  5.000e-03,  5.000e-03,
        5.000e-03, -5.000e-03,  5.000e-03, -5.000e-03,  5.000e-03,
        5.000e-03,  5.000e-03, -5.000e-03, -5.000e-03,  5.000e-03,
        5.000e-03, -4.114e-03, -5.000e-03,  5.000e-03,  5.000e-03,
       -5.000e-03, -5.000e-03, -5.000e-03, -5.000e-03, -4.919e-03,
       -5.000e-03, -5.000e-03, -5.000e-03,  5.000e-03, -5.000e-03,
       -5.000e-03,  5.000e-03,  5.000e-03, -5.000e-03, -5.000e-03,
       -5.000e-03, -5.000e-03, -3.942e-03, -5.000e-03, -5.000e

### Testando o modelo com os dados reais:

In [9]:
dados = pd.read_csv('dados_VETUSDT_15m.csv', usecols=['Date-Time', 'Close'], index_col=0)
dados.index = pd.to_datetime(dados.index)

dados = dados.loc['2021-10-01':, 'Close'].to_numpy()
#pd.Series(dados['Close']).to_numpy()
dados

array([0.09671, 0.09672, 0.09751, ..., 0.11818, 0.11892, 0.11886])

In [10]:
from utils_cripto import preparar_x_y_cripto
from utils_cripto import calcular_Sigma

import time

time_init = time.time()
x_vals, y_vals = preparar_x_y_cripto(dados)
print('Tempo "preparar_x_y_cripto":', time.time() - time_init, 's')

time_init = time.time()
Sigma = calcular_Sigma(x_vals)
print('Tempo "calcular_Sigma":', time.time() - time_init, 's')

print("OK!")

Tempo "preparar_x_y_cripto": 0.01500082015991211 s
Tempo "calcular_Sigma": 2.5611464977264404 s
OK!


##### Para problemas GRANDES, podemos utilizar:

In [11]:
from utils_cripto import preparar_x_y_cripto
from utils_cripto import numba_calcular_Sigma
from numba.typed import List

import time

time_init = time.time()
x_vals, y_vals = preparar_x_y_cripto(dados)
print('Tempo "preparar_x_y_cripto":', time.time() - time_init, 's')

time_init = time.time()
Sigma = numba_calcular_Sigma(List(x_vals))
print('Tempo "calcular_Sigma":', time.time() - time_init, 's')

print("OK!")

Tempo "preparar_x_y_cripto": 0.018001079559326172 s
Tempo "calcular_Sigma": 0.369020938873291 s
OK!


In [7]:
lambda_val = 1
modelo = Modelo_cripto_SVM(Sigma, y_vals, lambda_val)
d_vals = modelo.solve(log=1)

Academic license - for non-commercial use only - expires 2021-11-05
Using license file C:\Users\Eduardo\gurobi.lic
Parameter LogToConsole unchanged
   Value: 1  Min: 0  Max: 1  Default: 1
Gurobi Optimizer version 9.1.2 build v9.1.2rc0 (win64)
Thread count: 2 physical cores, 4 logical processors, using up to 4 threads
Optimize a model with 1608 rows, 1607 columns and 3214 nonzeros
Model fingerprint: 0x2ffaec27
Model has 1292028 quadratic objective terms
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e+00, 1e+00]
  QObjective range [1e+00, 3e+00]
  Bounds range     [3e-04, 3e-04]
  RHS range        [0e+00, 0e+00]
Presolve removed 1607 rows and 0 columns
Presolve time: 0.37s
Presolved: 1 rows, 1607 columns, 1607 nonzeros
Presolved model has 1292028 quadratic objective terms
Ordering time: 0.00s

Barrier statistics:
 Free vars  : 100
 AA' NZ     : 5.050e+03
 Factor NZ  : 5.151e+03 (roughly 1 MByte of memory)
 Factor Ops : 3.486e+05 (less than 1 second per it

In [8]:
d_vals

array([ 0.00031114, -0.00031107, -0.00031107, ...,  0.00031114,
        0.00031114, -0.00030984])